sudo: required
services:
  - docker

before_install:
  - docker build -t fabiohb/docker-react-example -f Dockerfile.dev .

script:
  - docker run fabiohb/docker-react-example npm run test -- --coverage