sudo: required
services:
  - docker

before_install:
  - docker build -t fabiohb/docker-react-example -f Dockerfile.dev .

script:
  - docker run -e CI=true fabiohb/docker-react-example npm run test -- --coverage

# deploy:
#   edge: true
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker-react-example"
#   env: "docker-react-example-env"
#   bucket_name: ""
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY